Testing github workflow

diff --git a/.github/workflows/custom_upstream_deploy.yml b/.github/workflows/custom_upstream_deploy.yml
--- a/.github/workflows/custom_upstream_deploy.yml
+++ b/.github/workflows/custom_upstream_deploy.yml
@@ -18,7 +18,7 @@ jobs:
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
-          php-version: "7.4"
+          php-version: "8.1"
 
       - name: Installing Terminus
         uses: kyletaylored/terminus-github-actions@main
@@ -26,24 +26,20 @@ jobs:
           pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
 
       - name: Clean up multidev
+        if: github.event_name == 'pull_request'
         run: |
-          if [ "${{ github.event_name }}" = "pull_request" ]; then
-            PR_BRANCH_NAME="pr-${{ github.event.pull_request.number }}"
-            CANARY_SITE=$(terminus org:site:list ${ORG_UUID} --format list --upstream ${UPSTREAM_UUID} --field name --tag canary | head -1)
-            if terminus env:info $CANARY_SITE.$PR_BRANCH_NAME > /dev/null 2>&1; then
-              terminus env:delete $CANARY_SITE.$PR_BRANCH_NAME -y --delete-branch
-            fi
+          PR_BRANCH_NAME="pr-${{ github.event.pull_request.number }}"
+          CANARY_SITE=$(terminus org:site:list ${ORG_UUID} --format list --upstream ${UPSTREAM_UUID} --field name --tag canary | head -1)
+          if terminus env:info $CANARY_SITE.$PR_BRANCH_NAME > /dev/null 2>&1; then
+            terminus env:delete $CANARY_SITE.$PR_BRANCH_NAME -y --delete-branch
+          fi
 
-            # Check if PR was merged
-            if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
-              echo "The PR was merged, continuing with deployment..."
-            else
-              echo "The PR was closed without merging. Exiting..."
-              exit 78 # Use exit code 78 to halt the workflow without failing
-            fi
+          # Check if PR was merged
+          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
+            echo "The PR was merged, continuing with deployment..."
           else
-            echo "This was triggered by a push to master. No multidev to clean up."
-            # Continue with the script for push to master
+            echo "The PR was closed without merging. Exiting..."
+            exit 78 # Use exit code 78 to halt the workflow without failing
           fi
         env:
           ORG_UUID: ${{ secrets.PANTHEON_ORG_UUID }}
@@ -61,6 +57,7 @@ jobs:
 
   deploy:
     runs-on: ubuntu-latest
+    if: github.event_name != 'pull_request'
     needs: build
     strategy:
       fail-fast: false
